services:
  api:
    container_name: quiz-your-mind_api_test
    environment: 
      - PGUSER=quizuser
      - PGHOST=db
      - PGPASSWORD=quizpass
      - PGDATABASE=quizDB
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    tty: true
  db:
    container_name: quiz_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quizDB
      - POSTGRES_PASSWORD=quizpass
volumes:
  test_db:
networks: 
  default:
    name: dev_test
